# Generated by Django 5.0.1 on 2024-03-26 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Monsters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, db_column='Name', null=True)),
                ('size', models.TextField(blank=True, db_column='Size', null=True)),
                ('type', models.TextField(blank=True, db_column='Type', null=True)),
                ('tag', models.TextField(blank=True, db_column='Tag', null=True)),
                ('alignment', models.TextField(blank=True, db_column='Alignment', null=True)),
                ('cr', models.TextField(blank=True, db_column='CR', null=True)),
                ('spellcaster', models.TextField(blank=True, db_column='Spellcaster', null=True)),
                ('legendary', models.TextField(blank=True, db_column='Legendary', null=True)),
                ('lair', models.TextField(blank=True, db_column='Lair', null=True)),
                ('unique', models.TextField(blank=True, db_column='Unique', null=True)),
                ('familiar', models.TextField(blank=True, db_column='Familiar', null=True)),
                ('template', models.TextField(blank=True, db_column='Template', null=True)),
                ('arctic', models.TextField(blank=True, db_column='Arctic', null=True)),
                ('coastal', models.TextField(blank=True, db_column='Coastal', null=True)),
                ('desert', models.TextField(blank=True, db_column='Desert', null=True)),
                ('forest', models.TextField(blank=True, db_column='Forest', null=True)),
                ('grassland', models.TextField(blank=True, db_column='Grassland', null=True)),
                ('hill', models.TextField(blank=True, db_column='Hill', null=True)),
                ('mountain', models.TextField(blank=True, db_column='Mountain', null=True)),
                ('swamp', models.TextField(blank=True, db_column='Swamp', null=True)),
                ('underdark', models.TextField(blank=True, db_column='Underdark', null=True)),
                ('underwater', models.TextField(blank=True, db_column='Underwater', null=True)),
                ('urban', models.TextField(blank=True, db_column='Urban', null=True)),
                ('other_plane', models.TextField(blank=True, db_column='Other Plane', null=True)),
                ('source', models.TextField(blank=True, db_column='Source', null=True)),
                ('page', models.TextField(blank=True, db_column='Page', null=True)),
            ],
        ),
    ]
