# Generated by Django 5.0.1 on 2024-03-26 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dungeonsanddragons', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Monsters',
            new_name='Monster',
        ),
    ]
